// <auto-generated />
namespace Yemek.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ekle14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ekle14));
        
        string IMigrationMetadata.Id
        {
            get { return "201705251740151_ekle14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
