// <auto-generated />
namespace Yemek.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ekle19 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ekle19));
        
        string IMigrationMetadata.Id
        {
            get { return "201706111842585_ekle19"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
