// <auto-generated />
namespace Protein.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ekle9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ekle9));
        
        string IMigrationMetadata.Id
        {
            get { return "201704232138525_ekle9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
