//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Jquery_VeriCekme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int RentID { get; set; }
        public int BookID { get; set; }
        public int UserID { get; set; }
        public System.DateTime RentDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public Nullable<int> Writer_WriterID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
        public virtual Writer Writer { get; set; }
    }
}
